#!/usr/bin/env python3
import json

# Read the JSON file
with open('askreddit_top_posts_2025.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Write the JavaScript file
with open('data.js', 'w', encoding='utf-8') as f:
    f.write('// Reddit AskReddit posts data\n')
    f.write('// Generated by scraper.py\n\n')
    f.write('const redditData = ')
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write(';\n')

print("Converted askreddit_top_posts_2025.json to data.js")
